apiVersion: configsync.gke.io/v1beta1
kind: RepoSync
metadata:
  name: repo-sync
  namespace: onlineboutique
spec:
  sourceFormat: unstructured
  sourceType: helm
  helm:
    repo: oci://northamerica-northeast1-docker.pkg.dev/acm-workshop-618-tenant/charts
    chart: onlineboutique
    version: 0.5.0
    releaseName: onlineboutique
    auth: gcpserviceaccount
    gcpServiceAccountEmail: helm-charts-reader@acm-workshop-618-tenant.iam.gserviceaccount.com
    values:
      cartDatabase:
        inClusterRedis:
          create: false
        connectionString: 10.24.184.43:6378
        externalRedisTlsOrigination:
          enable: true
          certificate: |
            -----BEGIN CERTIFICATE-----
MIIDnTCCAoWgAwIBAgIBADANBgkqhkiG9w0BAQsFADCBhTEtMCsGA1UELhMkNDM0
ZmM0OTMtOGY3Mi00NDc5LWIyZmQtZjU0MzQ3OTVkM2Q3MTEwLwYDVQQDEyhHb29n
bGUgQ2xvdWQgTWVtb3J5c3RvcmUgUmVkaXMgU2VydmVyIENBMRQwEgYDVQQKEwtH
b29nbGUsIEluYzELMAkGA1UEBhMCVVMwHhcNMjMwMTA1MjM1MjE5WhcNMzMwMTAy
MjM1MzE5WjCBhTEtMCsGA1UELhMkNDM0ZmM0OTMtOGY3Mi00NDc5LWIyZmQtZjU0
MzQ3OTVkM2Q3MTEwLwYDVQQDEyhHb29nbGUgQ2xvdWQgTWVtb3J5c3RvcmUgUmVk
aXMgU2VydmVyIENBMRQwEgYDVQQKEwtHb29nbGUsIEluYzELMAkGA1UEBhMCVVMw
ggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCLcXcnsjimHYN4AIjuQ1NX
0oQDba1ZPuEk/AiSBmfyVdKwoBUsZBaTVxvbbhsLH+7o/P1JqXnUo/7rNY1jzRZo
ly8hdMSo2unkF3s4K82TQbkkJGYrVMg8vD+Y0r63jTE8m3B2vrE2brjUQl1TN/tO
QVJKfN7uFJRHyaLDe3BDnan6kRMKrLsA4IrWQfASrqUsT91QDmOmFgT2VW6KGsGp
eKzqf8g4B0po3/xC7vveEW9pKFYZs3DyFfdCH1BYM3GzGyYsB2k3Py1Hm8Pe5kws
5QOoGgdZ+CDnv+9fCr8U2qkXrYMGnWrO//PZWgMK8oCPwee77gAp5ACoWpMTIbh5
AgMBAAGjFjAUMBIGA1UdEwEB/wQIMAYBAf8CAQAwDQYJKoZIhvcNAQELBQADggEB
AHbU47V+1ol85RFOX8osOIg4FxVbO8X1iUcCSUHu+F70GtMu4uBhbCVsLbWoDNKY
Nx5uWeovBtHPorsYVrif1tCGwx7WUrdHHBn1Ur/LOKbpIK9CA7mD4/3BF2lspVLi
WJGxxvi7mnDwgDDY87MRkIz5qYk1oJL3ME8KikI2KFUjGYBDh4dasgigqqWvBCtt
gYy/pJfVmGJD0+djBDOE+C2jtYDPGuLmRzamFCvwN2kRVQfSWshlssfyjNnH8Q47
jtfTO5j+eYQa2KeApdCN44zqxfCaZw0RvwR4WkFOJrKLCm4xykK3YaEPseX+JWti
5al77W2M1plmlFWNadHRviU=
-----END CERTIFICATE-----
          endpointAddress: 10.24.184.43
          endpointPort: 6378
      images:
        repository: northamerica-northeast1-docker.pkg.dev/acm-workshop-618-tenant/containers/onlineboutique
        tag: v0.5.0
      nativeGrpcHealthCheck: true
      seccompProfile:
        enable: true
      loadGenerator:
        checkFrontendInitContainer: false
      frontend:
        externalService: false
        virtualService:
          create: true
          gateway:
            name: asm-ingressgateway
            namespace: asm-ingress
            labelKey: asm
            labelValue: ingressgateway
          hosts:
          - onlineboutique.endpoints.acm-workshop-618-tenant.cloud.goog
      serviceAccounts:
        create: true
      authorizationPolicies:
        create: true
      networkPolicies:
        create: true
      sidecars:
        create: true
