apiVersion: configsync.gke.io/v1beta1
kind: RepoSync
metadata:
  name: repo-sync
  namespace: acm-workshop
spec:
  sourceFormat: unstructured
  sourceType: helm
  helm:
    repo: oci://northamerica-northeast1-docker.pkg.dev/acm-workshop-618-tenant/charts
    chart: acm-workshop
    version: 1.0.0-d371318
    releaseName: acm-workshop
    auth: gcpserviceaccount
    gcpServiceAccountEmail: helm-charts-reader@acm-workshop-618-tenant.iam.gserviceaccount.com
    values:
      container:
        image:
          repository: northamerica-northeast1-docker.pkg.dev/acm-workshop-618-tenant/containers
