apiVersion: constraints.gatekeeper.sh/v1beta1
kind: DestinationRuleTLSEnabled
metadata:
  name: destinationrule-tls-enabled
  annotations:
    policycontroller.gke.io/constraintData: |
      "{
        description: 'Prohibits disabling TLS for all hosts and host subsets in Istio DestinationRules.',
        remediation: 'Any DestinationRules should not disable TLS.'
      }"
spec:
  enforcementAction: deny
  match:
    kinds:
    - apiGroups:
      - networking.istio.io
      kinds:
      - DestinationRule
