apiVersion: constraints.gatekeeper.sh/v1beta1
kind: VirtualServiceWithHost
metadata:
  name: virtual-service-with-host
  annotations:
    policycontroller.gke.io/constraintData: |
      "{
        description: 'Requires that Istio VirtualService "hosts" must be set to something other than "*".',
        remediation: 'Any VirtualService shouldn't define the "hosts" with "*".'
      }"
spec:
  enforcementAction: deny
  match:
    kinds:
    - apiGroups:
      - networking.istio.io
      kinds:
      - VirtualService
